### ISSUE TITLE
If there is no popcount builtin find a implementation and add it to JUST agent.c

### ISSUE THREAD

**Issue by IsaacMcCracken** [IsaacMcCracken/KonaneBot#7]
This issue is pretty self explanitory

**Comment by IsaacMcCracken** [comment]
@PenutButer does it work with unsigned 64bit integers

**Comment by PenutButer** [comment]
__builtin_popcountll(unsigned long long) should work, tested with max unsigned 64 bit number on student server

**Comment by IsaacMcCracken** [comment]
alright thats good enough for me
